/**
 * PDF Theme Definitions
 * Each theme defines colors, fonts, margins, and styling for PDF output.
 * All fonts are sans-serif based for clean, modern readability.
 */

const pdfThemes = {
  // ─── LIGHT THEMES ───────────────────────────────────────────

  clean: {
    name: "Clean Modern",
    description: "Minimal and crisp — perfect for professional notes",
    category: "Light",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#1a1a2e",
    backgroundColor: "#ffffff",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#0f3460", fontSize: "2em", borderBottom: "3px solid #0f3460", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#16537e", fontSize: "1.6em", borderBottom: "2px solid #e0e6ed", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#1a6fa0", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#2185c5", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#3498db", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#5dade2", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#2980b9" },
    codeBlock: { background: "#f4f6f9", border: "1px solid #e1e5eb", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#eef2f7", color: "#c0392b", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #3498db", background: "#f0f7ff", color: "#2c3e50", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#d5dce6", headerBg: "#0f3460", headerColor: "#ffffff", stripedBg: "#f8fafc", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #e0e6ed", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#666",
    headerText: "",
    headerColor: "#999",
  },

  notion: {
    name: "Notion Style",
    description: "Inspired by Notion's clean aesthetic",
    category: "Light",
    fontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
    fontSize: "16px",
    lineHeight: "1.7",
    textColor: "#37352f",
    backgroundColor: "#ffffff",
    pageMargin: "30mm 25mm 30mm 25mm",
    h1: { color: "#37352f", fontSize: "2.2em", fontWeight: "700", borderBottom: "none", paddingBottom: "0", marginTop: "1.8em" },
    h2: { color: "#37352f", fontSize: "1.7em", fontWeight: "600", borderBottom: "1px solid #e9e5e0", paddingBottom: "4px", marginTop: "1.5em" },
    h3: { color: "#37352f", fontSize: "1.4em", fontWeight: "600", marginTop: "1.3em" },
    h4: { color: "#585754", fontSize: "1.15em", fontWeight: "600", marginTop: "1em" },
    h5: { color: "#787774", fontSize: "1.05em", fontWeight: "600", marginTop: "0.8em" },
    h6: { color: "#9b9a97", fontSize: "1em", fontWeight: "600", marginTop: "0.8em" },
    link: { color: "#2eaadc" },
    codeBlock: { background: "#f7f6f3", border: "none", borderRadius: "4px", fontFamily: "'SFMono-Regular', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px 20px" },
    inlineCode: { background: "#f7f6f3", color: "#eb5757", borderRadius: "3px", padding: "2px 5px", fontFamily: "'SFMono-Regular', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "3px solid #37352f", background: "#f7f6f3", color: "#37352f", padding: "12px 20px", borderRadius: "0" },
    table: { borderColor: "#e9e5e0", headerBg: "#f7f6f3", headerColor: "#37352f", stripedBg: "#fbfaf8", borderRadius: "0" },
    hr: { border: "none", borderTop: "1px solid #e9e5e0", margin: "1.5em 0" },
    pageNumber: true,
    pageNumberColor: "#9b9a97",
    headerText: "",
    headerColor: "#c4c3c0",
  },

  academic: {
    name: "Academic Paper",
    description: "Formal layout for research and academic writing",
    category: "Light",
    fontFamily: "'Source Sans Pro', 'Noto Sans', 'Segoe UI', Arial, sans-serif",
    fontSize: "14.5px",
    lineHeight: "1.8",
    textColor: "#1a1a1a",
    backgroundColor: "#ffffff",
    pageMargin: "30mm 25mm 30mm 25mm",
    h1: { color: "#1a1a1a", fontSize: "1.9em", borderBottom: "2px solid #1a1a1a", paddingBottom: "6px", marginTop: "2em", textTransform: "uppercase", letterSpacing: "1px" },
    h2: { color: "#2c2c2c", fontSize: "1.5em", borderBottom: "1px solid #999", paddingBottom: "4px", marginTop: "1.6em" },
    h3: { color: "#3a3a3a", fontSize: "1.25em", marginTop: "1.3em", fontStyle: "italic" },
    h4: { color: "#4a4a4a", fontSize: "1.1em", marginTop: "1em" },
    h5: { color: "#5a5a5a", fontSize: "1em", marginTop: "0.8em" },
    h6: { color: "#6a6a6a", fontSize: "0.95em", marginTop: "0.8em" },
    link: { color: "#1a5276" },
    codeBlock: { background: "#f5f5f5", border: "1px solid #ddd", borderRadius: "4px", fontFamily: "'Fira Code', 'Source Code Pro', Consolas, monospace", fontSize: "0.85em", padding: "14px" },
    inlineCode: { background: "#f0f0f0", color: "#c0392b", borderRadius: "3px", padding: "1px 5px", fontFamily: "'Fira Code', Consolas, monospace", fontSize: "0.85em" },
    blockquote: { borderLeft: "3px solid #555", background: "#fafafa", color: "#333", padding: "10px 18px", borderRadius: "0" },
    table: { borderColor: "#999", headerBg: "#2c3e50", headerColor: "#ffffff", stripedBg: "#f9f9f9", borderRadius: "0" },
    hr: { border: "none", borderTop: "1px solid #ccc", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#555",
    headerText: "",
    headerColor: "#999",
  },

  pastelDream: {
    name: "Pastel Dream",
    description: "Soft pastel colors — gentle on the eyes for long study sessions",
    category: "Light",
    fontFamily: "'Nunito Sans', 'Quicksand', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3d3d3d",
    backgroundColor: "#fefefe",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#6c5ce7", fontSize: "2em", borderBottom: "3px solid #a29bfe", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#e17055", fontSize: "1.6em", borderBottom: "2px solid #fab1a0", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#00b894", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#0984e3", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#fdcb6e", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#e84393", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#6c5ce7" },
    codeBlock: { background: "#f8f7ff", border: "1px solid #e8e5ff", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#f0eeff", color: "#6c5ce7", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #a29bfe", background: "#f8f7ff", color: "#555", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#e0dff5", headerBg: "#6c5ce7", headerColor: "#ffffff", stripedBg: "#faf9ff", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #a29bfe", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#a29bfe",
    headerText: "",
    headerColor: "#c8c5e2",
  },

  mint: {
    name: "Fresh Mint",
    description: "Cool mint green tones — refreshing and focused",
    category: "Light",
    fontFamily: "'DM Sans', 'Inter', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#2d3436",
    backgroundColor: "#ffffff",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#00b894", fontSize: "2em", borderBottom: "3px solid #00b894", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#00a381", fontSize: "1.6em", borderBottom: "2px solid #b2dfdb", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#009688", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#00897b", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#26a69a", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#4db6ac", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#00b894" },
    codeBlock: { background: "#f0faf8", border: "1px solid #b2dfdb", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#e8f8f5", color: "#00796b", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #00b894", background: "#f0faf8", color: "#2d3436", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#b2dfdb", headerBg: "#00b894", headerColor: "#ffffff", stripedBg: "#f5fcfa", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #b2dfdb", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#00b894",
    headerText: "",
    headerColor: "#80cbc4",
  },

  warmSunset: {
    name: "Warm Sunset",
    description: "Warm orange and amber tones — cozy study vibes",
    category: "Light",
    fontFamily: "'Rubik', 'Inter', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#2d2d2d",
    backgroundColor: "#fffdf9",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#e17055", fontSize: "2em", borderBottom: "3px solid #e17055", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#d35400", fontSize: "1.6em", borderBottom: "2px solid #f0c8a8", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#e67e22", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#f39c12", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#f1c40f", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#d4a017", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#e17055" },
    codeBlock: { background: "#fef9f3", border: "1px solid #f0d9c0", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#fef5ec", color: "#d35400", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #e17055", background: "#fef9f3", color: "#555", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#f0d9c0", headerBg: "#e17055", headerColor: "#ffffff", stripedBg: "#fffcf7", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #f0d9c0", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#e17055",
    headerText: "",
    headerColor: "#deb89a",
  },

  rosePetal: {
    name: "Rose Petal",
    description: "Elegant rose and pink tones — beautiful and refined",
    category: "Light",
    fontFamily: "'Poppins', 'Nunito Sans', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3d3d3d",
    backgroundColor: "#fffbfc",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#c44569", fontSize: "2em", borderBottom: "3px solid #c44569", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#e84393", fontSize: "1.6em", borderBottom: "2px solid #f8c8dc", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#fd79a8", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#e056a0", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#b83b5e", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#d4678c", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#c44569" },
    codeBlock: { background: "#fef5f8", border: "1px solid #f8d7e3", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#fef0f5", color: "#c44569", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #c44569", background: "#fef5f8", color: "#555", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#f8d7e3", headerBg: "#c44569", headerColor: "#ffffff", stripedBg: "#fefafc", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #f8c8dc", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#c44569",
    headerText: "",
    headerColor: "#e0a8bc",
  },

  ocean: {
    name: "Deep Ocean",
    description: "Deep blue tones — calm and focused for deep work",
    category: "Light",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#1e272e",
    backgroundColor: "#fdfdff",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#0a3d62", fontSize: "2em", borderBottom: "3px solid #0a3d62", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#1e5f8a", fontSize: "1.6em", borderBottom: "2px solid #b8d4e8", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#2980b9", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#3498db", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#5dade2", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#85c1e9", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#2980b9" },
    codeBlock: { background: "#f2f7fb", border: "1px solid #c8dce8", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#eaf2f8", color: "#1a5276", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #2980b9", background: "#f2f7fb", color: "#2c3e50", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#c8dce8", headerBg: "#0a3d62", headerColor: "#ffffff", stripedBg: "#f7fafc", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #c8dce8", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#2980b9",
    headerText: "",
    headerColor: "#85c1e9",
  },

  forest: {
    name: "Forest Green",
    description: "Natural green tones — earthy and grounding",
    category: "Light",
    fontFamily: "'DM Sans', 'Nunito Sans', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#2d3436",
    backgroundColor: "#fdfffe",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#1e6f50", fontSize: "2em", borderBottom: "3px solid #1e6f50", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#27ae60", fontSize: "1.6em", borderBottom: "2px solid #a9dfbf", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#2ecc71", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#58d68d", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#45b36b", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#76d7a0", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#27ae60" },
    codeBlock: { background: "#f0faf4", border: "1px solid #a9dfbf", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#eaf7ef", color: "#1e6f50", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #27ae60", background: "#f0faf4", color: "#2d3436", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#a9dfbf", headerBg: "#1e6f50", headerColor: "#ffffff", stripedBg: "#f5fcf8", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #a9dfbf", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#27ae60",
    headerText: "",
    headerColor: "#82d8a0",
  },

  lavender: {
    name: "Lavender Fields",
    description: "Soothing purple lavender — relaxing study atmosphere",
    category: "Light",
    fontFamily: "'Nunito Sans', 'Inter', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#2d2d3f",
    backgroundColor: "#fdfcff",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#5b2c8e", fontSize: "2em", borderBottom: "3px solid #7c3aed", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#7c3aed", fontSize: "1.6em", borderBottom: "2px solid #d4c5f9", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#8b5cf6", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#a78bfa", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#9061f9", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#c4b5fd", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#7c3aed" },
    codeBlock: { background: "#f8f5ff", border: "1px solid #e0d5f5", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#f3eeff", color: "#5b2c8e", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #7c3aed", background: "#f8f5ff", color: "#444", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#e0d5f5", headerBg: "#5b2c8e", headerColor: "#ffffff", stripedBg: "#fbf9ff", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #d4c5f9", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#7c3aed",
    headerText: "",
    headerColor: "#c4b5fd",
  },

  pastelSky: {
    name: "Pastel Sky",
    description: "Soft baby blue tones — airy and calm like a clear sky",
    category: "Light",
    fontFamily: "'Nunito Sans', 'Quicksand', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3b4252",
    backgroundColor: "#f8fbff",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#5b9bd5", fontSize: "2em", borderBottom: "3px solid #a8d1f0", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#6ba3d6", fontSize: "1.6em", borderBottom: "2px solid #c5e1f5", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#7bacd8", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#8bb8de", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#9cc4e4", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#aed0ea", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#5b9bd5" },
    codeBlock: { background: "#f0f6fd", border: "1px solid #d4e6f6", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#e8f1fb", color: "#3a7cc3", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #a8d1f0", background: "#f0f6fd", color: "#4a5568", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#d4e6f6", headerBg: "#5b9bd5", headerColor: "#ffffff", stripedBg: "#f5f9fe", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #a8d1f0", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#8bb8de",
    headerText: "",
    headerColor: "#b8d4ec",
  },

  pastelPeach: {
    name: "Pastel Peach",
    description: "Warm peach and apricot tones — soft and inviting",
    category: "Light",
    fontFamily: "'Poppins', 'Nunito Sans', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3d3535",
    backgroundColor: "#fffaf7",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#e8856c", fontSize: "2em", borderBottom: "3px solid #f4b8a6", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#d4785e", fontSize: "1.6em", borderBottom: "2px solid #f8d5c8", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#c97b65", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#d9917a", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#e5a590", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#f0b9a6", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#d4785e" },
    codeBlock: { background: "#fef5f0", border: "1px solid #f5d8cc", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#fdf0e8", color: "#c06040", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #f4b8a6", background: "#fef5f0", color: "#5a4a4a", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#f5d8cc", headerBg: "#e8856c", headerColor: "#ffffff", stripedBg: "#fffbf8", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #f4b8a6", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#d9917a",
    headerText: "",
    headerColor: "#e8c4b5",
  },

  pastelMeadow: {
    name: "Pastel Meadow",
    description: "Gentle sage green — fresh like a spring meadow",
    category: "Light",
    fontFamily: "'DM Sans', 'Nunito Sans', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3a3f3a",
    backgroundColor: "#f9fcf8",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#6b9e6b", fontSize: "2em", borderBottom: "3px solid #a8cfa8", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#7aaa7a", fontSize: "1.6em", borderBottom: "2px solid #c5e0c5", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#88b488", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#96be96", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#a4c8a4", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#b2d2b2", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#6b9e6b" },
    codeBlock: { background: "#f2f8f0", border: "1px solid #d0e5cc", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#eaf5e6", color: "#4a7a4a", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #a8cfa8", background: "#f2f8f0", color: "#4a5a4a", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#d0e5cc", headerBg: "#6b9e6b", headerColor: "#ffffff", stripedBg: "#f6faf5", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #a8cfa8", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#88b488",
    headerText: "",
    headerColor: "#b8d4b8",
  },

  pastelLilac: {
    name: "Pastel Lilac",
    description: "Delicate lilac and mauve — elegant and dreamy",
    category: "Light",
    fontFamily: "'Nunito Sans', 'Poppins', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3d3545",
    backgroundColor: "#fcf9ff",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#9b7ec8", fontSize: "2em", borderBottom: "3px solid #c4aee0", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#a88ed0", fontSize: "1.6em", borderBottom: "2px solid #d8c8ec", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#b59ed8", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#c2aee0", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#cfbee8", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#dccef0", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#9b7ec8" },
    codeBlock: { background: "#f6f1fc", border: "1px solid #e2d5f0", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#f0e8f8", color: "#7a5aaa", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #c4aee0", background: "#f6f1fc", color: "#5a4a68", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#e2d5f0", headerBg: "#9b7ec8", headerColor: "#ffffff", stripedBg: "#faf7fe", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #c4aee0", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#b59ed8",
    headerText: "",
    headerColor: "#d0c0e4",
  },

  pastelCoral: {
    name: "Pastel Coral",
    description: "Soft coral and blush pink — cheerful and lively",
    category: "Light",
    fontFamily: "'Quicksand', 'Nunito Sans', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3d3438",
    backgroundColor: "#fffbfa",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#e07070", fontSize: "2em", borderBottom: "3px solid #f0a8a8", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#d47878", fontSize: "1.6em", borderBottom: "2px solid #f5c4c4", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#e08888", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#e89898", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#f0a8a8", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#f5b8b8", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#d47878" },
    codeBlock: { background: "#fef3f2", border: "1px solid #f5d5d2", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#fdecea", color: "#c05050", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #f0a8a8", background: "#fef3f2", color: "#5a4548", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#f5d5d2", headerBg: "#e07070", headerColor: "#ffffff", stripedBg: "#fffaf9", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #f0a8a8", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#e08888",
    headerText: "",
    headerColor: "#e8b8b8",
  },

  pastelLemon: {
    name: "Pastel Lemon",
    description: "Sunny lemon and buttercream — warm and cheerful",
    category: "Light",
    fontFamily: "'DM Sans', 'Quicksand', 'Segoe UI', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#3d3a30",
    backgroundColor: "#fffef6",
    pageMargin: "25mm 22mm 25mm 22mm",
    h1: { color: "#c4a535", fontSize: "2em", borderBottom: "3px solid #e0cc70", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#b89e3a", fontSize: "1.6em", borderBottom: "2px solid #ecdfa0", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#c8ad48", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#d4bc58", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#e0cb68", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#e8d680", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#b89e3a" },
    codeBlock: { background: "#fdfbee", border: "1px solid #ece0a0", borderRadius: "10px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#fcf8e0", color: "#8a7520", borderRadius: "5px", padding: "2px 7px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #e0cc70", background: "#fdfbee", color: "#5a5540", padding: "12px 20px", borderRadius: "0 10px 10px 0" },
    table: { borderColor: "#ece0a0", headerBg: "#c4a535", headerColor: "#ffffff", stripedBg: "#fefdf5", borderRadius: "10px" },
    hr: { border: "none", borderTop: "2px dashed #e0cc70", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#c8ad48",
    headerText: "",
    headerColor: "#d8c880",
  },

  // ─── DARK THEMES ────────────────────────────────────────────

  darkMode: {
    name: "Dark Mode",
    description: "Classic dark theme — easy on the eyes at night",
    category: "Dark",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#e0e0e0",
    backgroundColor: "#1a1a2e",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#82b1ff", fontSize: "2em", borderBottom: "3px solid #82b1ff", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#80cbc4", fontSize: "1.6em", borderBottom: "2px solid #37474f", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#a5d6a7", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#ce93d8", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#ffcc80", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#ef9a9a", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#82b1ff" },
    codeBlock: { background: "#0d1117", border: "1px solid #30363d", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#21262d", color: "#ff7b72", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #82b1ff", background: "#16213e", color: "#b0bec5", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#30363d", headerBg: "#21262d", headerColor: "#e0e0e0", stripedBg: "#161b22", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #30363d", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#666",
    headerText: "",
    headerColor: "#444",
  },

  dracula: {
    name: "Dracula",
    description: "Popular Dracula color scheme — vibrant on dark",
    category: "Dark",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#f8f8f2",
    backgroundColor: "#282a36",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#ff79c6", fontSize: "2em", borderBottom: "3px solid #ff79c6", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#bd93f9", fontSize: "1.6em", borderBottom: "2px solid #44475a", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#50fa7b", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#8be9fd", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#ffb86c", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#f1fa8c", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#8be9fd" },
    codeBlock: { background: "#1e1f29", border: "1px solid #44475a", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#44475a", color: "#ff79c6", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #bd93f9", background: "#1e1f29", color: "#f8f8f2", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#44475a", headerBg: "#44475a", headerColor: "#f8f8f2", stripedBg: "#21222c", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #44475a", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#6272a4",
    headerText: "",
    headerColor: "#44475a",
  },

  nord: {
    name: "Nord",
    description: "Arctic-inspired Nord palette — cool and serene",
    category: "Dark",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#d8dee9",
    backgroundColor: "#2e3440",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#88c0d0", fontSize: "2em", borderBottom: "3px solid #88c0d0", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#81a1c1", fontSize: "1.6em", borderBottom: "2px solid #3b4252", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#a3be8c", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#ebcb8b", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#b48ead", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#bf616a", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#88c0d0" },
    codeBlock: { background: "#272c36", border: "1px solid #3b4252", borderRadius: "8px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#3b4252", color: "#bf616a", borderRadius: "4px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #88c0d0", background: "#272c36", color: "#d8dee9", padding: "12px 20px", borderRadius: "0 8px 8px 0" },
    table: { borderColor: "#3b4252", headerBg: "#3b4252", headerColor: "#eceff4", stripedBg: "#2a2f3a", borderRadius: "8px" },
    hr: { border: "none", borderTop: "2px solid #3b4252", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#4c566a",
    headerText: "",
    headerColor: "#3b4252",
  },

  solarizedDark: {
    name: "Solarized Dark",
    description: "Ethan Schoonover's Solarized — scientifically designed",
    category: "Dark",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', sans-serif",
    fontSize: "15px",
    lineHeight: "1.75",
    textColor: "#839496",
    backgroundColor: "#002b36",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#268bd2", fontSize: "2em", borderBottom: "3px solid #268bd2", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#2aa198", fontSize: "1.6em", borderBottom: "2px solid #073642", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#859900", fontSize: "1.35em", marginTop: "1.2em" },
    h4: { color: "#b58900", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#cb4b16", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#d33682", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#268bd2" },
    codeBlock: { background: "#073642", border: "1px solid #094959", borderRadius: "6px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.88em", padding: "16px" },
    inlineCode: { background: "#073642", color: "#cb4b16", borderRadius: "3px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.88em" },
    blockquote: { borderLeft: "4px solid #268bd2", background: "#073642", color: "#93a1a1", padding: "12px 20px", borderRadius: "0 6px 6px 0" },
    table: { borderColor: "#094959", headerBg: "#073642", headerColor: "#93a1a1", stripedBg: "#003845", borderRadius: "6px" },
    hr: { border: "none", borderTop: "2px solid #094959", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#586e75",
    headerText: "",
    headerColor: "#073642",
  },

  // ─── SPECIAL THEMES ─────────────────────────────────────────

  newspaper: {
    name: "Newspaper",
    description: "Classic newspaper column style — timeless readability",
    category: "Special",
    fontFamily: "'Source Sans Pro', 'Noto Sans', 'Segoe UI', Arial, sans-serif",
    fontSize: "14.5px",
    lineHeight: "1.7",
    textColor: "#1a1a1a",
    backgroundColor: "#faf8f5",
    pageMargin: "20mm 18mm 20mm 18mm",
    h1: { color: "#1a1a1a", fontSize: "2.4em", borderBottom: "4px double #1a1a1a", paddingBottom: "8px", marginTop: "1.5em", textTransform: "uppercase", letterSpacing: "2px" },
    h2: { color: "#333", fontSize: "1.6em", borderBottom: "1px solid #999", paddingBottom: "4px", marginTop: "1.3em", textTransform: "uppercase", letterSpacing: "1px" },
    h3: { color: "#444", fontSize: "1.3em", marginTop: "1.2em" },
    h4: { color: "#555", fontSize: "1.15em", marginTop: "1em" },
    h5: { color: "#666", fontSize: "1.05em", marginTop: "0.8em" },
    h6: { color: "#777", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#1a5276" },
    codeBlock: { background: "#f0ede8", border: "1px solid #d5d0c8", borderRadius: "2px", fontFamily: "'Fira Code', 'Source Code Pro', Consolas, monospace", fontSize: "0.85em", padding: "14px" },
    inlineCode: { background: "#ede9e3", color: "#8b0000", borderRadius: "2px", padding: "1px 5px", fontFamily: "'Fira Code', Consolas, monospace", fontSize: "0.85em" },
    blockquote: { borderLeft: "3px solid #1a1a1a", background: "#f5f2ed", color: "#333", padding: "10px 18px", borderRadius: "0" },
    table: { borderColor: "#999", headerBg: "#1a1a1a", headerColor: "#faf8f5", stripedBg: "#f5f2ed", borderRadius: "0" },
    hr: { border: "none", borderTop: "3px double #1a1a1a", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#555",
    headerText: "",
    headerColor: "#999",
  },

  highContrast: {
    name: "High Contrast",
    description: "Maximum readability — bold and clear for accessibility",
    category: "Special",
    fontFamily: "'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontSize: "16px",
    lineHeight: "1.8",
    textColor: "#000000",
    backgroundColor: "#ffffff",
    pageMargin: "25mm 20mm 25mm 20mm",
    h1: { color: "#000000", fontSize: "2.2em", borderBottom: "4px solid #000000", paddingBottom: "8px", marginTop: "1.5em" },
    h2: { color: "#1a1a1a", fontSize: "1.7em", borderBottom: "3px solid #333", paddingBottom: "6px", marginTop: "1.3em" },
    h3: { color: "#0000cc", fontSize: "1.4em", marginTop: "1.2em" },
    h4: { color: "#006600", fontSize: "1.2em", marginTop: "1em" },
    h5: { color: "#990000", fontSize: "1.1em", marginTop: "0.8em" },
    h6: { color: "#660066", fontSize: "1em", marginTop: "0.8em" },
    link: { color: "#0000ee" },
    codeBlock: { background: "#f0f0f0", border: "2px solid #333", borderRadius: "4px", fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace", fontSize: "0.9em", padding: "16px" },
    inlineCode: { background: "#e8e8e8", color: "#cc0000", borderRadius: "3px", padding: "2px 6px", fontFamily: "'JetBrains Mono', Consolas, monospace", fontSize: "0.9em" },
    blockquote: { borderLeft: "5px solid #000", background: "#f5f5f5", color: "#000", padding: "12px 20px", borderRadius: "0" },
    table: { borderColor: "#000", headerBg: "#000000", headerColor: "#ffffff", stripedBg: "#f0f0f0", borderRadius: "0" },
    hr: { border: "none", borderTop: "3px solid #000", margin: "2em 0" },
    pageNumber: true,
    pageNumberColor: "#000",
    headerText: "",
    headerColor: "#666",
  },
};

export default pdfThemes;
